### ISSUE TITLE
Does not respond to `object` changes

### ISSUE THREAD

**Issue by joshvillbrandt** [awendland/angular-json-tree#2]
It appears that this directive currently does not respond to `object` changes which minimizes its utility.

**Comment by joshvillbrandt** [comment]
I ended up using this instead: https://github.com/Goldark/ng-json-explorer

**Comment by awendland** [comment]
The object data is provided in a two-way binding, so it should update to object changes (though I may be wrong). The [gh-pages](https://github.com/awendland/angular-json-tree/tree/gh-pages) demo uses this functionality to support loading different objects.

**Comment by baluvanan** [comment]
Faced  the same issue when we were updating the scope variable [fixed] by adding a ng-if to the directive to check for the data load is complete
