### ISSUE TITLE
Cannot get injected by wiredep and gulp

### ISSUE THREAD

**Issue by rcholic** [awendland/angular-json-tree#7]
I installed this repo using bower in my project and I use gulp/wiredep to inject the bower dependencies into my `index.html` file. I found the dependency `angular-json-tree` does not get injected. I guess this repo may have some problem with its bower settings. Could the author please check into this issue?

Link to the **wiredep** page: https://github.com/taptapship/wiredep:

A Bower package may not properly list its dependencies in its bower.json file.
A Bower package may not specify a main property in its bower.json file.

**Comment by henry-martinez** [comment]
Same here... the bower.json "main" path is pointing to src/... instead of build/...
I changed it locally as a workaround
